# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "English spellchecker"
en = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for English, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
en = "TRANSLATE: A spellchecker for English, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.en"

[windows]
system_product_code = "{B5DB55D0-ED3B-4587-9FC3-ED494EF401BA}_is1"
legacy_product_codes = [
    { value = "A91E54BF-5601-4F72-983B-6DF768069564", kind = "nsis" },
    { value = "D9BC1B80-8D9A-49B4-9D7C-FEF527A0A904", kind = "nsis" }
]

[package.speller]
name = "English"
version = "0.1.1"

[package.grammar]
name = "English"
version = "0.1.0"

[package.tts-text-proc]
name = "English"
version = "0.1.0"
