template = "https://github.com/giellalt/template-lang-und"
rev_id = 276
template_sha = "c9932c142bad82b28a2c8b49e60ad8895a749b1e"

[replacements]
__GLOTTOLOG_ID__ = "stan1293"
__REPO__ = "lang-eng"
__UND2C__ = "en"
__UNDEFINED__ = "English"
__UND__ = "eng"
