template = "https://github.com/giellalt/template-lang-und"
rev_id = 277
template_sha = "c0f383639e245d1daebce6e2006904e442eef1fd"

[replacements]
__GLOTTOLOG_ID__ = "stan1293"
__REPO__ = "lang-eng"
__UND2C__ = "en"
__UNDEFINED__ = "English"
__UND__ = "eng"
