template = "https://github.com/giellalt/template-lang-und"
rev_id = 259
template_sha = "dbafdbc00bdeb17f80ec54b2fd5d6ae330f25f51"

[replacements]
__GLOTTOLOG_ID__ = "stan1293"
__REPO__ = "lang-eng"
__UND2C__ = "en"
__UNDEFINED__ = "English"
__UND__ = "eng"
